version: 2
jobs:
  build:
    docker:
    #  - image: circleci/node:7.10
      - image: bissessd/pluralsight-docker-ci:latest
    working_directory: ~/repo

    steps:
      - checkout
      #- run: npm install
      #- run: npm test
      - run: mocha

   # deployment:
   #   dockerhub:
   #   branch: master
   #   commands:
   #     - $DOCKER_HUB_TRIGGER
  