
workflows:
  version: 2
  node-ios:
    jobs:
      - build:
          filters:
            branches:
              only: dev
      - ios:
          type: approval
          requires:
            - build

#build:
#   deployment:
#    dockerhub:
#    branch: master
#    commands:
#      - $DOCKER_HUB_TRIGGER
#test:
#  - run:
#    - mocha
