# ~/.circleci/config.yml
  version: 2
  Circle_Test:
    jobs:
      deployment:
        branch: master
        commands:
          - $DOCKER_HUB_TRIGGER
      test:
        override:
          - mocha
    
