
version: 2.1
orbs:
  hello: circleci/hello-build@.0.0.5 # uses the circleci/buildpack-deps Docker image

workflows:
  "Hello Workflow":
    jobs:
      - hello/hello-build

#build:
#   deployment:
#    dockerhub:
#    branch: master
#    commands:
#      - $DOCKER_HUB_TRIGGER
#test:
#  - run:
#    - mocha
