version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
      #- image: bissessd/pluralsight-docker-ci:latest # use my own image on Docker Hub
    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install   #works with CircleCI Image
      - run: npm test      #works with CircleCI Image
      #- run: mocha          # Mocha Testing Framework

   